export const ICON_OPTIONS = {
  star: 'FaStar',
  heart: 'FaHeart',
  bookmark: 'FaBookmark',
  film: 'FaFilm',
  list: 'FaList',
  trophy: 'FaTrophy',
  fire: 'FaFire',
  clock: 'FaClock',
  thumbsUp: 'FaThumbsUp',
  thumbsDown: 'FaThumbsDown',
  lock: 'FaLock',
  globe: 'FaGlobe',
  tag: 'FaTag',
  trash: 'FaTrash',
}
